"""Create data models

Revision ID: a1b2c3d4e5f6
Revises: f8d9c6f257e0
Create Date: 2026-02-14 11:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'f8d9c6f257e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('instrument_type', sa.Enum('ETF', 'MF', name='instrument_type_enum'), nullable=False),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_isin'), 'instruments', ['isin'], unique=False)
    op.create_index(op.f('ix_instruments_symbol'), 'instruments', ['symbol'], unique=True)

    op.create_table('symbol_cache',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('instrument_type', sa.Enum('ETF', 'MF', 'INDEX', name='symbol_instrument_type_enum'), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbol_cache_symbol'), 'symbol_cache', ['symbol'], unique=True)

    op.create_table('backtest_results',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('instrument_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('strategy_name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('equity_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('benchmark_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('xirr', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('summary_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_results_instrument_id'), 'backtest_results', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_backtest_results_user_id'), 'backtest_results', ['user_id'], unique=False)

    op.create_table('historical_prices',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('instrument_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('high', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('low', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('close', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('adjusted_close', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'date', name='_instrument_date_uc')
    )
    op.create_index(op.f('ix_historical_prices_date'), 'historical_prices', ['date'], unique=False)
    op.create_index(op.f('ix_historical_prices_instrument_id'), 'historical_prices', ['instrument_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('backtest_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('instrument_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_type', sa.Enum('BUY', 'SELL', 'DIVIDEND', 'SIP', name='transaction_type_enum'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fees', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtest_results.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_backtest_id'), 'transactions', ['backtest_id'], unique=False)
    op.create_index(op.f('ix_transactions_instrument_id'), 'transactions', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_instrument_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_backtest_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_historical_prices_instrument_id'), table_name='historical_prices')
    op.drop_index(op.f('ix_historical_prices_date'), table_name='historical_prices')
    op.drop_table('historical_prices')
    op.drop_index(op.f('ix_backtest_results_user_id'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_instrument_id'), table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_index(op.f('ix_symbol_cache_symbol'), table_name='symbol_cache')
    op.drop_table('symbol_cache')
    op.drop_index(op.f('ix_instruments_symbol'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_isin'), table_name='instruments')
    op.drop_table('instruments')
    # ### end Alembic commands ###